spring:
  application:
    name: ChatWith

claude-code:
  path: D:\software\nodejs\node_modules\@anthropic-ai\claude-code\bin\claude.exe
  timeout: 300000
  skillsDir: .claude/skills

letta-server:
  url: http://localhost:8283
  timeout: 300000
  model: deepseek/deepseek-v4-pro
  embedding: letta/letta-free
  system-prompt-path: .letta/sora-system-prompt.md

setting:
  skillName : sora-perspective
  systemPrompt : "请用中文回答!!!!!! 请用中文回答!!!! 请用中文回答!!! 请用中文回答!! 如果是日文请翻译为中文!!!"


tts:
  url: http://127.0.0.1:9880
  ref-audio-path: D:\idea_java_project\IntelliJ IDEA 2024.1.4\projects\ChatWith\src\main\resources\SR000104.wav
  prompt-text: "家の近くを散歩してただけだから、それに自分が歩いてきた道を戻るくらいはできる。"
  prompt-lang: ja
  text-lang: ja
  media-type: wav
  speed-factor: 1.0

baidu:
  translate:
    app-id: 20260512002612061
    secret-key: k4pkBuhUsHhaxaw54XLL
    api-url: https://fanyi-api.baidu.com/api/trans/vip/translate

audio:
  store-dir: audio-store

server:
  port: 8080
