spring:
  application:
    name: ChatWith

claude-code:
  path: D:\software\nodejs\node_modules\@anthropic-ai\claude-code\bin\claude.exe
  timeout: 300000
  skillsDir: .claude/skills

setting:
  skillName : sora-perspective
  systemPrompt : "请用中文回答!!!!!! 请用中文回答!!!! 请用中文回答!!! 请用中文回答!! 如果是日文请翻译为中文!!!"


server:
  port: 8080
